Debugg article creation error
Creating a new article caused the view to throw an
error.

Error message:
django.db.utils.IntegrityError: null value in
column "owner_id" of relation "api_article"
violates not-null constraint

Removing argument depth = 1 from ArticleSerializer
resolved this issue.

In the process of finding the error I dropped and
created the db.

Also, img_url and sub_title fields were added to
the Article model, serializer, and view
respectively.